import { HealBall }    from './HealBall.js';
import { KKyeongChanBall } from './김경찬.js';
import { LeeJunWooBall } from './이준우.js';
import { HongYunkiBall } from './홍윤기.js';
import { HwangAInBall } from './황아인.js';
import { ChoisihyeongBall } from './최시형.js';
import { ParkMinjunBall } from './박민준.js';
import { KoSunhoBall } from './고선호.js';
import { OsuenghunBall } from './오승훈.js';
import { YangjaewonBall } from './양재원.js';
import { LimjihuBall } from './임지후.js';
import { RamenBall } from './송규원.js';
import { ZimbabweBall} from './이재용.js';
import { KimSooHwanBall } from './김수환.js';

export const BALL_REGISTRY = [
  {
    id:          'HeavyOx',
    name:        '김경찬',
    icon:        '-',
    color:       '#999999',
    type:        '묵직 탱커',
    description: '단단하고 무거운 김경찬입니다. 우람찬 팔을 휘둘러 공격하며 그의 뛰어난 성대와 갑작스런 돌파구는 아무도 막지 못합니다!',
    stats: { hp: 420, atk: 50, spd: 22, def: 94 },
    image: "./assets/image/김경찬이미지.jpg",
    skill: {
      icon:        '🐗',
      name:        '분노의 돌진',
      cooldown:    10,
      description: '주변에 있는 상대를 음파 공격으로 혼란시킨 후 황소처럼 돌진하여 120의 피해를 줍니다. 속도가 충분히 빠르고 멀리있다면 돌진을 피할 수 있지 않을까요?',
      tags:        ['음파', '돌진', '김경찬'],
    },
    Class: KKyeongChanBall,
  },
  {
    id:          'LegGrabber',
    name:        '이준우',
    icon:        '-',
    color:       '#999999',
    type:        '하체 딜러',
    description: '생생하고 날렵한 이준우입니다. 그는 평소에 펀치하여 공격하나 변태준우 모드가 발동된다면 그를 막을 수 있는 자는 극히 드뭅니다.',
    stats: { hp: 280, atk: 81, spd: 60, def: 54 },
    image: "./assets/image/이준우이미지.jpg",
    skill: {
      icon:        '🫣',
      name:        '변준 On',
      cooldown:    8,
      description: '갑작스러운 흥분으로 인해 변준모드가 가동되었습니다! 변준모드에서는 속력이 더 빨라지며 일정거리에 있는 최대 2명의 대상을 다리로 붙잡아 강력하게 조여 총 90의 피해를 줍니다. 멀리서 공격한다면 다리 쪼임을 피할 수 있지 않을까요?',
      tags:        ['다리', '돌진', '변준'],
    },
    Class: LeeJunWooBall,
  },
  {
    id:          'SideburnsGrower',
    name:        '홍윤기',
    icon:        '-',
    color:       '#999999',
    type:        '구렛나루 딜러',
    description: '머리가 몸에 비해 매우 큰 홍윤기 입니다. 그는 평소에는 잠잠하지만, 그의 심기를 건드리는 일이 발생한다면 제 2의 인격인 구렛나루를 소환합니다.',
    stats: { hp: 250, atk: 15, spd: 35, def: 30 },
    image: "./assets/image/홍윤기이미지.jpg",
    skill: {
      icon:        '🗿',
      name:        '구렛나루 폭풍 성장',
      cooldown:    8,
      description: '윤기의 분노가 전장을 휘엎습니다! 일시적으로 구렛나루가 인체를 초월할 정도로 자라나며 자아를 가집니다. 자아를 가진 구렛나루는 회전하며 적에게 20의 피해를 주고 부딪힌 후 방향 바꿉니다. 구렛나루 회전 방향과 같은 방향으로 움직인다면 구렛나루를 피할 수 있지 않을까요?',
      tags:        ['구렛나루', '성장', '회오리'],
    },
    Class: HongYunkiBall,
  },
  {
    id:          'ShortKicker',
    name:        '황아인',
    icon:        '-',
    color:       '#999999',
    type:        '발차기 딜러',
    description: '작지만 그 힘이 응축된 황아인입니다. 평소엔 매우 착하고 온순하지만, 불미의 사건이 일어난다면 그녀의 치명적인 앞차기를 시전합니다. 시간이 흐를 수록 그녀의 복수심은 커집니다.',
    stats: { hp: 190, atk: 150, spd: 50, def: 30 },
    image: "./assets/image/황아인이미지.jpg",
    skill: {
      icon:        '🦶',
      name:        '보복의 앞차기',
      cooldown:    2,
      description: '황아인의 복수심이 임계치를 넘었습니다! 짧은 거리에 있는 대상들을 향해 앞차기를 시전하며 그 데미지는 복수심에 비례합니다. 그녀의 복수심은 시간이 흐름에 따라 증가하며 복수 게이지를 증가시킵니다. 복수 게이지는 12초일때 최대가 되며 최대 데미지는 150까지 증가합니다. 복수 게이지가 약할 때 부딪힌다면 위력은 약해지지 않을까요?',
      tags:        ['복수심', '게이지', '앞차기'],
    },
    Class: HwangAInBall,
  },
  {
    id:          'ExBoyFriendSoccerTeam',
    name:        '최시형',
    icon:        '-',
    color:       '#999999',
    type:        '축구단 소환사',
    description: '아주 착한 생명과 학생 최시형입니다. 겉보기엔 평범해보이지만 그녀 뒤에 숨겨진 암흑의 과거는 전혀 평범하지 않습니다. 한 전설에 따르면, 그녀의 전남친들로 축구단을 만들 수 있다고 합니다.',
    stats: { hp: 225, atk: 18, spd: 72, def: 30 },
    image: "./assets/image/최시형이미지.png",
    skill: {
      icon:        '⚽',
      name:        '과거를 향한 축구단',
      cooldown:    2,
      description: '그 전설이 진짜로 일어났습니다. 일정 시간이 흐른 후 그녀는 하늘에서 축구선수 5명을 소환합니다. 축구선수는 인접한 불특정 다수의 대상에게 돌진하며 폭발한 후 그 대상에게 18의 피해를 줍니다. 인원이 많다면 축구선수가 분산되지 않을까요?',
      tags:        ['축구 선수', '소환', '카미카제'],
    },
    Class: ChoisihyeongBall,
  },
  {
    id:          'BasketRusher',
    name:        '박민준',
    icon:        '-',
    color:       '#999999',
    type:        '농구 돌격병',
    description: '매우 강력한 농구의 고수 박민준입니다. 농구공과 함께 단련된 그의 매우 빠른 침투 속도와 궤멸적인 실압근은 타의 추종을 불허합니다. 가속할 시간이 충분하다면 그를 막을 수 있는 자는 없을 것입니다.',
    stats: { hp: 290, atk: 354, spd: 90, def: 0 },
    image: "./assets/image/박민준이미지.jpg",
    skill: {
      icon:        '🏀',
      name:        '바스킷 드리블 콤보',
      cooldown:    3,
      description: '박민준이 가속하기 시작합니다. 농구공을 드리블 하며 3초가 흐른 후 콤보가 +1이 됩니다. 콤보는 최대 10까지 증가할 수 있으며 타깃 대상에게 닿으면 궤멸적인 데미지와 함께 콤보는 -1됩니다. 콤보는 박민준의 이동 속도와 충돌 데미지를 증가시킵니다. 데미지는 콤보가 2일 때: 12, 4일 때: 48, 6일 때: 96, 10일 때: 384입니다. 초반에 많이 부딪힌다면 콤보를 낭비할 수 있지 않을까요?',
      tags:        ['농구', '드리블', '콤보'],
    },
    Class: ParkMinjunBall,
  },
  {
    id:          'SweatPig',
    name:        '고선호',
    icon:        '-',
    color:       '#999999',
    type:        '육수 탱커',
    description: '악성 지방의 소유자 고선호입니다. 그 우람찬 몸매를 부각시키려는 것인지 최근들어 운동을 하고 있습니다. 그의 러닝 페이스는 갈 수록 처참한데요, 이때 그는 포기하지 않고 열심히 달려나간답니다.',
    stats: { hp: 350, atk: 15, spd: 20, def: 30 },
    image: "./assets/image/고선호이미지.jpg",
    skill: {
      icon:        '🐷',
      name:        '돼지 육수의 웅덩이',
      cooldown:    14,
      description: '고선호가 유산소 운동을 하기 시작했습니다. 일정시간동안 속도가 근소하게 빨라지며, 우람찬 몸매를 아직 받아들이기 힘든지 금방 지쳐 원상태로 복귀합니다. 운동을 할 때 그에게서 나온 땀(육수)이 총 3번 떨어지며, 멀리 퍼져나갑니다. 땀에 닿은 적은 속도가 느려지고 데미지 15를 받습니다. 만일 체력이 35% 이하로 내려갈시 선호는 격분하여 빠른 속도로 전장을 활보하며 빠른 속도로 강화된 땀을 흘리게 됩니다. 강화된 땀은 일정 시간 이후 터지며 상대에게 피해를 줍니다.',
      tags:        ['농구', '드리블', '콤보'],
    },
    Class: KoSunhoBall,
  },
  {
    id:          'CharmingBighead',
    name:        '오승훈',
    icon:        '-',
    color:       '#999999',
    type:        '서큐버스',
    description: '사람들을 유혹하는 대두의 원조, 오승훈입니다. 그의 우람찬 몸매와 대두는 있는 사람으로 하여금 매혹의 요소가 될 수 있습니다. 그는 많은 남자들을 유혹하여 끌어들이고 이후 좌절감을 느끼게 하여 남성들에게 상처를 주는 나쁜 서큐버스라는 전설이 있습니다.',
    stats: { hp: 310, atk: 80, spd: 25, def: 30 },
    image: "./assets/image/오승훈이미지.jpg",
    skill: {
      icon:        '💕',
      name:        '매혹 대두의 키스',
      cooldown:    5,
      description: '오승훈의 대두 유혹이 시작되었습니다! 일정 범위 내에 있는 적들을 매혹시켜 자신에게로 끌어들이고 이후 대상에게 치명적인 키스를 하여 80의 피해를 줍니다.',
      tags:        ['키스', '뽀뽀', '사랑'],
    },
    Class: OsuenghunBall,
  },
  {
    id:          'BlackSoccerSniper',
    name:        '양재원',
    icon:        '-',
    color:       '#999999',
    type:        '축구공 스나이퍼',
    description: '밤의 축구의 대가 양재원입니다. 검은 피부와 함께 성장해온 축구 실력은 그의 독특한 형질로 자리잡아 있습니다. 그의 눈은 오로지 축구공을 향하며 앞으로도 축구공을 향에 걸어 나갈 것을 약속합니다.',
    stats: { hp: 240, atk: 155, spd: 40, def: 0 },
    image: "./assets/image/양재원이미지.png",
    skill: {
      icon: '⚽',
      name:        '준비하시고.. 쏘세요!',
      cooldown:    12,
      description: '양재원의 암흑 축구가 시작되었습니다. 전장 전체를 암흑으로 만들어 은신합니다. 은신 상태의 양재원은 무적상태가 됩니다. 이후 슛파워를 충전한 뒤, 가장 가까운 적을 향해 엄청난 속도로 축구공을 날려보내 175의 파멸적인 피해량을 입힙니다.',
      tags:        ['농구', '드리블', '콤보'],
    },
    Class: YangjaewonBall,
  },
  {
    id:          'GoOutGambler',
    name:        '임지후',
    icon:        '-',
    color:       '#999999',
    type:        '고백 도박꾼',
    description: '고백 마스터 임지후입니다. 매일매일 늘어가는 그의 고백 실력은 타의 추종을 불허합니다. 특히 오랫동안 봐온 누군가에게 고백을 하는 것을 참 좋아합니다.',
    stats: { hp: 250, atk: 0, spd: 40, def: 0 },
    image: "./assets/image/임지후이미지.jpg",
    skill: {
      icon: '🎲',
      name:        '수시 원서형 고백',
      cooldown:    6,
      description: '임지후가 마음을 다잡고 사랑 고백을 시작합니다! 가장 인접한 대상에게 접근하여 고백 공격을 시작합니다. 고백 공격받은 대상은 99%의 확률로 고백 거절을 시전합니다. 고백 거절한 대상은 10~60의 피해를 받으며 그에 반하여 임지후는 5~15의 체력을 회복하고 이후에 마음의 치유시간이 6초가 소요됩니다. 만일 대상이 "최시형"이라면 데미지가 2배로 들어갑니다. 그러나 1%의 확률로 상대는 고백을 받아주며, 이때 임지후는 경기에서 무조건 승리합니다.',
      tags:        ['고백', '무작위', '이론상 최강'],
    },
    Class: LimjihuBall,
  },
  {
    id:          'RamenThrower',
    name:        '송규원',
    icon:        '-',
    color:       '#999999',
    type:        '라면 투척병',
    description: '동하FC 출신 송규원입니다. 그가 기숙사에서 사감쌤의 눈을 피해 최애 라면인 카구리를 무단 취식을 하는 것을 본다면 매우 대담하다는 것을 느낄 수 있습니다.',
    stats: { hp: 275, atk: 18, spd: 72, def: 30 },
    image: "./assets/image/송규원이미지.jpg",
    skill: {
      icon: '🍜',
      name:        '카구리 흠뻑쇼',
      cooldown:    6,
      description: '송규원이 자신의 최애 라면인 카구리를 공중으로 던집니다. 던져진 카구리는 일정 시간 후에 지면으로 낙하하며 낙하한 순간에 3개로 분열하고 폭발하여 주변 적에게 60의 피해를 줍니다.',
      tags:        ['카구리', '라면', '분열'],
    },
    Class: RamenBall,
  },
  {
    id:          'MoneyMan',
    name:        '이재용',
    icon:        '-',
    color:       '#999999',
    type:        '인플레이터',
    description: '삼성출신...? 인줄 알았으나 그저 평범한 충곽인인 1111 이재용입니다. 그의 뛰어난 예측력과 엄청난 재력을 생각해보면 그의 이름은 결코 평범하지 않다는 걸 알 수 있습니다.',
    stats: { hp: 230, atk: 1, spd: 100, def: 30 },
    image: "./assets/image/이재용임시이미지.png",
    skill: {
      icon: '💸',
      name:        '짐바브웨 달러의 재채기 임플레이션',
      cooldown:    6,
      description: '이재용이 재채기를 하여 품에 숨겨있던 짐바브웨 달러가 12방향으로 분출합니다. 이때 데미지는 돈의 가치만큼 주고 기본적으로 35이며 재채기를 할 때마다 돈의 가치가 변동합니다. 돈의 가치는 최소 1, 최대 100입니다.',
      tags:        ['이재용', '짐바브웨달러', '인플레이션'],
    },
    Class: ZimbabweBall,
  },
    {
    id:          'EggQuizzer',
    name:        '김수환',
    icon:        '-',
    color:       '#999999',
    type:        '에그 체인저',
    description: '그저 평범한 김수환입니다. 날계란을 못먹습니다.',
    stats: { hp: 220, atk: 0, spd: 30, def: 0 },
    image: "./assets/image/김수환이미지2.png",
    skill: {
      icon: '⏳',
      name:        '선택의 계란',
      cooldown:    10,
      description: '김수환이 계란을 던져 선택의 시간을 시작합니다. 이 시간은 전장을 4개로 분할하며 실패 타일 2개, 생존 타일 1개, 럭키 타일 1개를 갖습니다. 일정시간 후 그 타일 위에 있는 대상을 판단합니다. 만일 실패 타일일 경우 레이저를 쏘아 최대 체력의 34%의 데미지를 부여합니다. 반면 생존 타일일 경우 데미지를 부여하지 않으며, 럭키 타일일 경우 체력 40을 회복합니다.',
      tags:        ['계란', '사분면', '선택'],
    },
    Class: KimSooHwanBall,
  },
];
